// Generated by CoffeeScript 2.5.1
(function() {
  var MessageManager;

  module.exports = MessageManager = class MessageManager {
    constructor(app) {
      this.app = app;
      this.messages = {};
    }

    _middleware_check_user(socket, next) {
      if (!this.app.users.is_registered(socket.id)) {
        return next(new Error('User not registered'));
      } else {
        return next();
      }
    }

    // Register a new message list
    register(uid) {
      if (!(uid in this.messages)) {
        return this.messages[uid] = {
          count: 0
        };
      }
    }

    
      // Add a message
    add(uid) {
      if (!(uid in this.messages)) {
        throw "User is not registered";
      }
      return this.messages[uid].count = ++this.messages[uid].count;
    }

    
      // Retrieve number of messages sent
    count(uid) {
      if (!(uid in this.messages)) {
        throw "User is not registered";
      }
      return this.messages[uid].count;
    }

  };

}).call(this);
