// Generated by CoffeeScript 2.5.1
(function() {
  var UserManager;

  module.exports = UserManager = class UserManager {
    constructor(app) {
      this.app = app;
      this.users = {};
    }

    // Check a nickname already exists
    exists(nickname) {
      var uid;
      for (uid in this.users) {
        if (this.users[uid].nickname === nickname) {
          return true;
        }
      }
      return false;
    }

    
      // Register a new user
    register(user_id, nickname, imgid) {
      if (!(user_id in this.users)) {
        this.users[user_id] = {
          "nickname": nickname,
          "status": "online",
          "uid": user_id,
          "imgid": imgid
        };
      }
      return this.users[user_id];
    }

    
      // Retrieve specific user info
    get_user(user_id) {
      if (!(user_id in this.users)) {
        throw "User does not exists";
      }
      return this.users[user_id];
    }

    
      // Check if a user is already registered
    is_registered(user_id) {
      if (user_id in this.users) {
        return true;
      }
      return false;
    }

    
      // Remove a user
    remove(user_id) {
      if (!(user_id in this.users)) {
        throw "User does not exists";
      }
      return delete this.users[user_id];
    }

    
      // Change user current status
    status(user_id, current_status) {
      if (!(user_id in this.users)) {
        throw "User does not exists";
      }
      return this.users[user_id].status = current_status;
    }

    
      // Return users list
    list() {
      return this.users;
    }

  };

}).call(this);
