// Generated by CoffeeScript 2.5.1
(function() {
  var SingleChat,
    indexOf = [].indexOf;

  module.exports = SingleChat = class SingleChat {
    constructor() {
      this.users = [];
    }

    _middleware(socket, next) {
      var ref;
      if (ref = socket.id, indexOf.call(this.users, ref) < 0) {
        return next(new Error('forbidden'));
      } else {
        return next();
      }
    }

    message(socket, text) {
      console.log(`Someone say: ${text}.`);
      return socket.broadcast.emit('message', text);
    }

    logout(socket) {
      var ref;
      if (ref = socket.id, indexOf.call(this.users, ref) >= 0) {
        return this.users.splice(this.users.indexOf(socket.id), 1);
      }
    }

    _notAccessible(socket) {
      return console.error("You should not be here !!");
    }

  };

}).call(this);
