// Generated by CoffeeScript 2.5.1
(function() {
  var CoreChat;

  module.exports = CoreChat = class CoreChat {
    constructor() {
      this.users = [];
    }

    register(socket, data) {
      if (data.nickname) {
        return this.users.push(data.nickname);
      }
    }

  };

}).call(this);
